name: docs

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Generate tsdoc
      uses: borales/actions-yarn/@v2.0.0
      with:
        cmd: build-docs
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v2.8.0
      env:
        PERSONAL_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./docs
      with:
        emptyCommits: false
        keepFiles: true
