name: publish

on:
  release:
    types: published

env:
  NPM_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install
      uses: borales/actions-yarn/@v2.0.0
      with:
        cmd: install
    - name: Build js & d.ts files
      uses: borales/actions-yarn/@v2.0.0
      with:
        cmd: build-publish
    - name: Publish
      run: npm publish
    - name: notification
      if: cancelled() == false
      uses: xinthink/action-telegram@v1.1
      with:
        botToken: ${{ secrets.TelegramBotToken }}
        chatId: ${{ secrets.TelegramTarget }}
        jobStatus: ${{ job.status }}
