name: publish

on:
  push:
    branches: publish

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      uses: borales/actions-yarn/@v2.0.0
      with:
        cmd: build
